___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Упражнения по NumPy

Давайте проверим Ваши знания NumPy. Мы начнём с достаточно простых задач, и плавно перейдём к более сложным.

<div class="alert alert-danger" style="margin: 10px"><strong>ВАЖНОЕ ЗАМЕЧАНИЕ!</strong> Пожалуйста не запускайте ячейки, которые располагаются <br> непосредственно над ожидаемым результатом, иначе Вы удалите этот ожидаемый результат!</div>

#### 1. Импортируйте NumPy as np

In [2]:
import numpy as np

#### 2. Создайте массив из 10 нулей

In [91]:
# Напишите Ваше решение в этой ячейке
ar1 = np.zeros(10)
ar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создайте массив из 10 единиц

In [90]:
# Напишите Ваше решение в этой ячейке
ar2 = np.ones(10)
ar2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создайте массив из 10 пятёрок

In [89]:
# Напишите Ваше решение в этой ячейке
ar3 = np.full(10, 5)
ar3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создайте массив целых чисел от 10 до 50 включительно

In [88]:
# Напишите Ваше решение в этой ячейке
ar4 = np.arange(10,50,1)
ar4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [87]:
# Напишите Ваше решение в этой ячейке
ar5 = np.arange(10,51,2)
ar5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [86]:
# Напишите Ваше решение в этой ячейке
ar6 = np.arange(9).reshape(3,3)
ar6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создайте единичную матрицу размером 3x3

In [85]:
# Напишите Ваше решение в этой ячейке
ar7 = np.eye(3)
ar7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1<br><br>&emsp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [84]:
# Напишите Ваше решение в этой ячейке
ar8 = np.random.rand(1)
ar8

array([0.01936696])

In [9]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.65248055])

#### 10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения<br><br>&emsp;&ensp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [83]:
# Напишите Ваше решение в этой ячейке
ar9 = np.random.rand(25)
ar9

array([0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ,
       0.09834683, 0.42110763, 0.95788953, 0.53316528, 0.69187711,
       0.31551563, 0.68650093, 0.83462567, 0.01828828, 0.75014431,
       0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601,
       0.44789353, 0.9085955 , 0.29361415, 0.28777534, 0.13002857])

In [10]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Создайте указанную ниже матрицу:

In [96]:
# Напишите Ваше решение в этой ячейке
ar11 = np.arange(0.01, 1.01,0.01).reshape((10,10))
ar11

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [97]:
# Напишите Ваше решение в этой ячейке
ar12 = np.linspace(0.0, 1.0, 20)
ar12

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Индексация Numpy

Здесь Вы будете работать с некоторой матрицей - чтобы создать её, запустите следующую ячейку! После этого мы попросим Вас воспроизвести несколько результатов работы с этой матрицей:

In [23]:
# ЗАПУСТИТЕ ЭТУ ЯЧЕЙКУ - ЭТО СОЗДАНИЕ МАТРИЦЫ ДЛЯ СЛЕДУЮЩИХ ЗАДАНИЙ
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу (подсказка - используйте индексацию).

In [81]:
# Напишите Ваше решение в этой ячейке
mat[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [80]:
# Напишите Ваше решение в этой ячейке
print(mat[3, 4])

20


In [15]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


20

#### 15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [78]:
# Напишите Ваше решение в этой ячейке
mat[0:3, 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [16]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [77]:
# Напишите Ваше решение в этой ячейке
mat[4]

array([21, 22, 23, 24, 25])

In [17]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([21, 22, 23, 24, 25])

#### 17. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [76]:
# Напишите Ваше решение в этой ячейке
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции в NumPy

#### 18. Найдите сумму всех чисел в матрице mat

In [44]:
# Напишите Ваше решение в этой ячейке
print(mat.sum())

325


In [19]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


325

#### 19. Найдите среднеквадратичное отклонение значений в матрице mat

In [45]:
# Напишите Ваше решение в этой ячейке
print(np.std(mat))

7.211102550927978


In [20]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


7.211102550927978

#### 20. Найдите сумму каждой из колонок в матрице mat

In [75]:
# Напишите Ваше решение в этой ячейке
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([55, 60, 65, 70, 75])

## Бонусный вопрос

Мы много работали со случайными данными в numpy, но есть ли способ каждый раз получать одни и те же "случайные" результаты? [Для подсказки нажмите здесь](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [56]:
# Напишите Ваше решение в этой ячейке
np.random.seed(1)

# Отличная работа!