In [3]:
import numpy as np

1. Создайте массив из 12 чисел, распределённых равномерно в диапазоне [-5, 5].

In [4]:
a1 = np.linspace(-5, 5, 12)
print(a1)

[-5.         -4.09090909 -3.18181818 -2.27272727 -1.36363636 -0.45454545
  0.45454545  1.36363636  2.27272727  3.18181818  4.09090909  5.        ]


2. Создайте массив 3×3 со значениями от 0 до 8.

In [5]:
a2 = np.arange(9).reshape(3, 3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Создайте массив из 10 чисел, начиная с 5 с шагом 3.

In [6]:
a3 = np.arange(5, 5 + 10 * 3, 3)
print(a3)

[ 5  8 11 14 17 20 23 26 29 32]


4. Найдите дисперсию и стандартное отклонение массива [2, 4, 6, 8, 10].

In [9]:
arr4 = np.array([2, 4, 6, 8, 10])
print("дисперсия =", arr4.var(), ", стандартное отклонение =", arr4.std())

дисперсия = 8.0 , стандартное отклонение = 2.8284271247461903


5. Создайте матрицу 3×3, найдите сумму её элементов по диагонали.

In [11]:
m5 = np.arange(1, 10).reshape(3, 3)
print("матрица\n", m5)
print("сумма по главной диагонали =", np.trace(m5))

матрица
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
сумма по главной диагонали = 15


6. Объедините три массива в один одномерный.

In [12]:
b1 = np.array([1, 2, 3])
b2 = np.array([4, 5, 6])
b3 = np.array([7, 8, 9])
merged = np.concatenate([b1, b2, b3])
print(merged)

[1 2 3 4 5 6 7 8 9]


7. Создайте массив 5×5 и вычислите кумулятивную сумму по строкам.

In [15]:
m7 = np.arange(1, 26).reshape(5, 5)
sum_rows = np.cumsum(m7, axis=1)
print("исходная матрица\n", m7)
print("   кумулятивная сумма по строкам\n", sum_rows)

исходная матрица
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
   кумулятивная сумма по строкам
 [[  1   3   6  10  15]
 [  6  13  21  30  40]
 [ 11  23  36  50  65]
 [ 16  33  51  70  90]
 [ 21  43  66  90 115]]


8. Из массива [1, 2, 3, 4, 5, 6] получите массив [1, 4, 9, 16, 25, 36] без циклов.

In [16]:
arr8 = np.arange(1, 7)
squares = arr8 ** 2
print(squares)

[ 1  4  9 16 25 36]


9. Замените все NaN в массиве [1, np.nan, 3, np.nan, 5] на 0.

In [18]:
arr9 = np.array([1, np.nan, 3, np.nan, 5])
cleaned = np.nan_to_num(arr9, nan=0)
print(cleaned)

[1. 0. 3. 0. 5.]


10. Создайте матрицу 4×4 и поверните её на 90 градусов.

In [19]:
m10 = np.arange(1, 17).reshape(4, 4)
rotated = np.rot90(m10)
print("исходная\n", m10)
print("повёрнутая на 90°\n", rotated)

исходная
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
повёрнутая на 90°
 [[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
